### ISSUE TITLE
Scheduled github action not working

### ISSUE THREAD

**Issue by kwkwan** [paneron/extensions.paneron.org#2]
The cron job defined in yaml file does not work as expected.

**Comment by ribose-jeffreylau** [comment]
It works now that the repo has seen some activities.

**Comment by strogonoff** [comment]
@CAMOBAP could we add a keep-alive workflow here too, similar to https://github.com/paneron/paneron.org/issues/2?

EDIT: Actually, keep-alive is not working for paneron.org, so perhaps we need to find a better solution and apply it to both sites🤔

**Comment by strogonoff** [comment]
The reason it may actually be more important to keep these builds alive compared to paneron.org site is that extensions.paneron.org is currently (not necessarily forever) used by Paneron to determine current versions of available extensions.

**Comment by strogonoff** [comment]
For now, I 1) manually enabled workflow and 2) ran workflow by hand from GHA GUI. (But we shouldn’t rely on this…)

**Comment by CAMOBAP** [comment]
keep-alive workflow added

**Comment by strogonoff** [comment]
@CAMOBAP I guess keep-alive doesn’t work, because it weren’t building in the last 3 weeks…

**Comment by strogonoff** [comment]
Can you confirm that manual action is required?

**Comment by CAMOBAP** [comment]
@strogonoff keep-alive workflow was removed in https://github.com/paneron/extensions.paneron.org/commit/d8453375cf7e484d25cbfcf542683ea0bd3439de by @kwkwan

**Comment by strogonoff** [comment]
Got it, I overlooked that fact…

**Comment by ribose-jeffreylau** [comment]
Looks like it's working.  Closing.

<img width="987" alt="Screenshot 2024-12-04 at 12 09 00" src="https://github.com/user-attachments/assets/61bb3b80-6605-44b6-9580-c3ade97aeabd">
