### ISSUE TITLE
Workflow “is waiting for github-pages deployment approval”

### ISSUE THREAD

**Issue by strogonoff** [paneron/extensions.paneron.org#6]
Might be that someone with access to repository settings can solve this?

<img width="1229" alt="Screenshot 2024-09-04 at 15 29 16" src="https://github.com/user-attachments/assets/a3a7c1e7-6bc4-4657-9648-a73d1deede3f">

**Comment by strogonoff** [comment]
I’ve no idea what state the build is in, Github’s GHA history is currently very weird for this repository.

**Comment by ronaldtse** [comment]
@strogonoff you should have access now, try again?

**Comment by ronaldtse** [comment]
It says this now... Maybe there is some issue with the workflow dependencies.

<img width="1168" alt="Screenshot 2024-09-04 at 3 32 35 PM" src="https://github.com/user-attachments/assets/87e0713b-4f2e-40da-b4b8-9194e0fb7e95">

**Comment by ronaldtse** [comment]
I see what you saw too:

<img width="1166" alt="image" src="https://github.com/user-attachments/assets/6405b912-cca4-47d0-a2c6-3307e71cdebf">

Perhaps cancel and restart?

**Comment by strogonoff** [comment]
I didn’t see anything approval-related in settings, so perhaps just stuck workflow. Cancelled & it seems to have succeeded.
