### ISSUE TITLE
(URGENT!!!) Site shows empty page

### ISSUE THREAD

**Issue by ribose-jeffreylau** [paneron/extensions.paneron.org#7]
Possibly related: https://github.com/paneron/site-builder/issues/6

## Screenshot

<img width="1351" alt="Screenshot 2024-12-04 at 12 11 48" src="https://github.com/user-attachments/assets/bd4b31c3-c77a-44df-9b0a-8341d4d00319">

**Comment by ronaldtse** [comment]
What's going on?

**Comment by ribose-jeffreylau** [comment]
There are no errors except for the `Error.captureStackTrace` one, and I don't think that's the cause of the problem.  But it's a problem that can be reproduced locally.

**Comment by ribose-jeffreylau** [comment]
I can see that npmjs.com's search API may be where the problem is.

See: https://github.com/npm/registry/blob/main/docs/REGISTRY-API.md#get-v1search

We use the following two requests:

- https://registry.npmjs.com/-/v1/search?text=scope:riboseinc%20paneron-extension
- https://registry.npmjs.com/-/v1/search?text=scope:paneron%20extension

but both seem to return all 40,000+ results, which is clearly wrong.

**Comment by ribose-jeffreylau** [comment]
Looks like another way of enumerating extensions is needed.

Something like this may be useful: https://github.com/npm/cli/blob/2af31dd30f4c226f43ce7295cd0b5fbb3f3cb2a6/workspaces/libnpmsearch/lib/index.js#L6

**Comment by strogonoff** [comment]
Should be fixed now.

Apparently, NPM search API stopped supporting `scope:` query, and for our query it was returning a bunch of unrelated packages which paginated so that we couldn’t see our extensions during build.

**Comment by strogonoff** [comment]
The main body of the fix is https://github.com/paneron/extensions.paneron.org/commit/6af4633ecb2da82e32faf5a0388c70e8453a3eef

**Comment by strogonoff** [comment]
> Looks like another way of enumerating extensions is needed.
> 
> Something like this may be useful: https://github.com/npm/cli/blob/2af31dd30f4c226f43ce7295cd0b5fbb3f3cb2a6/workspaces/libnpmsearch/lib/index.js#L6

@ribose-jeffreylau unfortunately, `libnpmsearch` does not offer feature parity with the `scope:` queries that we relied on up until now. It’s very fuzzy full-text search. Even searching for `"paneron-extension"`, even with quotes, returns a bunch of unrelated stuff that just happens to have “extension” in its name.

**Comment by ribose-jeffreylau** [comment]
@strogonoff I couldn't seem to find any documentation or changelogs detailing this change to the search API.
